# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventureQuest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='question_id',
            field=models.IntegerField(),
        ),
    ]
