# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 10:56
from __future__ import unicode_literals

import adventureQuest.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventureQuest', '0003_post_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=adventureQuest.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventureQuest.Quest'),
        ),
    ]
