# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventureQuest', '0003_auto_20170320_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscores',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
