# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventureQuest', '0004_auto_20170316_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='name',
            field=models.CharField(default='new Quest', max_length=200),
        ),
    ]
