# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventureQuest', '0006_auto_20170316_1349'),
        ('adventureQuest', '0002_auto_20170316_1226'),
    ]

    operations = [
    ]
