# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-21 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventureQuest', '0006_auto_20170320_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
