# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventureQuest', '0007_merge_20170317_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='hint',
            field=models.CharField(default='No hint available', max_length=128),
        ),
        migrations.AddField(
            model_name='riddle',
            name='instruction',
            field=models.CharField(default='No specific instructions available', max_length=128),
        ),
        migrations.AddField(
            model_name='riddle',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
