# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventureQuest', '0008_auto_20170317_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='score',
        ),
    ]
