# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventureQuest', '0011_auto_20170319_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='start_point',
            field=models.CharField(default='here', max_length=120),
        ),
    ]
